name: 步步宝

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 0-12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Dean12321/AutoRun.git ~/AutoRun
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/AutoRun
          npm install
          npm install cron
          npm install request
      - name: '运行 【步步宝】'
        run: |
          cd ~/AutoRun   
          node Task/bububao.js
    env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

          
          
